apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-aspnetcore-deployment
spec:
  replicas: 2 
  selector:
     matchLabels:
        app: kafka-aspnetcore-pod
  template:
    metadata:
      labels:
        app: kafka-aspnetcore-pod
    spec:
      containers:
        - name: producer-container
          image: training007.azurecr.io/producer:0.0.1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
        - name: consumer-container
          image: training007.azurecr.io/consumer:0.0.1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 80   
        - name: zookeeper
          image: training007.azurecr.io/zookeeper:0.0.1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 2181    
        - name: kafka
          image: training007.azurecr.io/kafka:0.0.1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 9092          
---
apiVersion: v1
kind: Service
metadata:
    name: hello-aspnetcore-service
spec:
  ports:
    - name: http-port-producer 
      port: 9081
      targetPort: 80
    - name: http-port-consumer
      port: 9082
      targetPort: 80  
    - name: zookeeper
      port: 2081
      targetPort: 2081
    - name: kafka
      port: 9092
      targetPort: 9092     
  selector:
    app: kafka-aspnetcore-pod
  type: LoadBalancer  